# Generated by Django 4.1.7 on 2023-07-03 11:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('summary', ckeditor.fields.RichTextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('indra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bmw.indra')),
            ],
        ),
    ]
