# Generated by Django 4.1.7 on 2023-07-06 02:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('summary', ckeditor.fields.RichTextField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
